name: Tests

on:
  - push

jobs:
  test:
    strategy:
      matrix:
        runs-on: [macos-latest, windows-latest]
        python-version: ['3.8', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with flake8
      run: |
        flake8 src
    - name: Plot tests
      run: |
        python -m pytest tests -s
